language: r
cache: packages
pandoc_version: 2.9.2.1

env:
  global:
    - secure: "C8CqrD7IOI+Hq0V5I31HPfkfBlsRiJdhrorVW9GP5yxu+QfUG7tfo13oc2lYS6tYMqh8hpxNRLnr7rYseT7S9SGC2vr/dJnuXEMHm/a1xqXfrdN91GynmxQpZOOx2S4gfhEby4FLC+lM3vaJMAAJSuIFLOAsvjpSMILw9VXvzIMnHsCfJ+8cL497H3UzZ8pT8zoGeTwgL1ZyrMoXeozGsbzK3I24K79RzeCDQsl+fp+0s3qxXhpZIsU/PMHkR4LhCuejMfuNhytn+2gPDx7sTy6ee1wzrkLSGh7o/lrOFu5R4t63lokZjkj6WIrtsCVo/m4JMb2XbcGwd3bSxgf5DK7mhvIGl3ih9t7FP5UV7EnHecOnWF105PJg+pgjqQt4iHEqlOcrOiNvY9dS5pGE2h55tJ5cHmzXNcAcuUwm+Ycu/4AH79ncyQlRgI/Anx4X1laGJohm6AcXP5Ei8rwG25QNqFgXuuebkm5jPmZECU2O6EfWPRAug7+07iWJ8iHzzBPgc2gKucsdVkEsLSAT3Z0bFruZQXKyUc9uIXGUmRSUeX7lLYucmP3eBpPeP/KDGwoaIjJkX8n1ruoV1HUgs3aLMGFOr/sdmLJvbL4Q4BS8Y7za/+yVut6VcNnZJBV/pvPNpc5r171JBuD+YLwkXL0hD+upRwowcWutImu3acU="

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh