--- 
title: "Bookdown Playground"
author: "Lennart Wittkuhn"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
biblio-style: apalike
link-citations: yes
github-repo: lnnrtwttkhn/bookdown-playground
description: "Experiments with DataLad, R bookdown and Travis CI"
output:
  bookdown::gitbook:
    config:
      toc:
        collapse: subsection
        scroll_highlight: yes
        before: null
        after: null
      toolbar:
        position: fixed
      edit : null
      download: null
      search: yes
      fontsettings:
        theme: white
        family: sans
        size: 2
      sharing:
        facebook: yes
        github: yes
        twitter: yes
        linkedin: no
        weibo: no
        instapaper: no
        vk: no
        all: ['facebook', 'twitter', 'linkedin', 'weibo', 'instapaper']
      info: yes
      code_folding: "hide"

---
```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Superdataset

Welcome to my Bookdown Playground!

## `index.Rmd`

This is the content of the `index.Rmd` file in the root of the repo.


## Things I learned:

1. You need at least one `#` main heading
  - If you don't specify one main markdown heading, e.g., in the `index.Rmd`, the `index.Rmd` will not be rendered as an `index.html` which in turn, however, is *neeed* for your website to properly show up.
1. Things to consider when adding subdatasets / git submodules
  - Good news: Travis CI clones Git submodules by default
  - When using subdatasets aka. git submodules you should add `options(bookdown.render.file_scope = FALSE);` to your `Rscript` command, e.g., use:
  ```bash
  Rscript -e "options(bookdown.render.file_scope = FALSE); bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
  ```
  - Also, although this is vague advice, don't add too many nested subdatasets (certainly not the *same* dataset) do avoid creating a long recursion down into the rabbit hole of submodules.
